security:
  encoders:
    App\Entity\User:
      algorithm: auto
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: Username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      provider: app_user_provider
      logout:
        path: /logout
      guard:
        authenticators:
          - App\Security\LoginAuthenticator
      remember_me:
        secret: "%kernel_secret"
        lifetime: 2592000
    # activate different ways to authenticate
    # https://symfony.com/doc/current/security.html#firewalls-authentication
    # https://symfony.com/doc/current/security/impersonating_user.html
    # switch_user: true

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/logout, roles: ROLE_USER }
    - { path: ^/(reports|report/*), roles: ROLE_ADMIN }
    - { path: ^/(profile|upload-new), roles: ROLE_USER }
    - { path: ^/check-view/*, roles: ROLE_USER }
    - { path: ^/admin/*, roles: ROLE_MODERATOR }
    - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/profile, roles: ROLE_USER }
